# Generated by Django 4.2.2 on 2023-06-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatIds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caffeName", models.CharField(max_length=500)),
                ("chatId", models.CharField(max_length=500)),
            ],
        ),
    ]
